### ISSUE TITLE
درخواست

### ISSUE THREAD

**Issue by Saeedroshan1906** [Azumi67/Direct_Chisel#1]
سلام به azumi عزیز ازتون درخواست ساخت یک اسکریپت ایجاد اپلود فیک بر بستر tcp رو دارم نسخه ای بالاتر از نامیزون چون دیگه اون رو راحت شناسایی میکنن

**Comment by Azumi67** [comment]
سلام . این مورد را باید مطالعه کرد و اسکریپت و کد های دیگران رو بررسی کرد و من نمیدونم که ایا وقت چنین کاری رو دارم یا خیر. چون هنوز چند تا اسکریپت و کارهایی که میخوام انجام بدم هم انجام نشده.
