### ISSUE TITLE
ناپایدار شدن سورس بعد از اپدیت 2 هفته پیش

### ISSUE THREAD

**Issue by 2EXEN** [Azumi67/Direct_Chisel#2]
سلام 

من مدت زیادی بود داشتم از تانل استفاده میکردم اما دیروز مجبور به ری بیلد سرور شدم و دوباره از اول کانفیگ کردم اما سورس تانل ناپایدار شده و مثل سابق نیست

**Comment by Azumi67** [comment]
سلام. من اپدیتی نکردم

**Comment by 2EXEN** [comment]
پس چطور سرور های جدید که دارم کانفیگ میکنم مشکل میخورن یه مشکل که قبلا روی ریورس وجود داشت (یه مدت کار میکنه یدفه غیرفعال میشه و قطعی وصلی شروع میشه) سرور های قدیمی که کانفیگ کردم چنین مشکلی ندیدم داشته باشن
