### ISSUE TITLE
حذف ریست تایمر

### ISSUE THREAD

**Issue by mk66-coding** [Azumi67/Direct_Chisel#3]
سلام. استاد عزیز.اقا من ریست تایمر رو چجوری حذفش کنم. تعداد کاربر هام کم هستند خانوادگی.میخواستم هی قطع و وصل نشه. چجوری چه دستوری بزنم که ریست تایمر رو حذف کنم؟

**Comment by Azumi67** [comment]
سلام . آقا نیستم. داخل crontab -e برید و اون دستور مربوط به ریست رو حذف کنید .
