### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by Saeedroshan1906** [Azumi67/Direct_Chisel#4]
سلام خانم ازومی میگم من مشکلم با ریست تایمه مثلا رو دو ساعته یهویی ارتباط تانل قطع میشه کلا حتی رو ۲۰ دقیقه هم همین منوال حالا اگه کاملا از کرون تب حذف بشه چه اتفاقی میوفته

**Comment by Azumi67** [comment]
سلام. ریست تایم چنین کاری نمیکنه و مشکل شما جای دیگری هست . لطفاً لاگ های سرویس خود را بررسی کنید .

**Comment by mohamadm0meni** [comment]
> سلام. ریست تایم چنین کاری نمیکنه و مشکل شما جای دیگری هست . لطفاً لاگ های سرویس خود را بررسی کنید .

چگونه لاگ های سرویس خود را بررسی کنیم ؟
