### ISSUE TITLE
ریست تایم

### ISSUE THREAD

**Issue by alphamanrays** [Azumi67/Direct_Chisel#5]
سلام و درود خدمت شما 
بهترین ریست تایم کدوم هست؟ و اینکه سرعت چیزل تانل داخل اسپید تست درست نشون نمیده ؟ م
منون میشم راهی برای تست سرعت بفرمایید
 خیلی ممنون از شما

**Comment by mohamadm0meni** [comment]
> سلام و درود خدمت شما بهترین ریست تایم کدوم هست؟ و اینکه سرعت چیزل تانل داخل اسپید تست درست نشون نمیده ؟ م منون میشم راهی برای تست سرعت بفرمایید خیلی ممنون از شما

تجربه ای که من داشتم این بود که سرور خارج خیلی نیاز به ریست تایم نداره من زمانی دایرکت چیزل میزدم روی 48 ساعت قرار میدادم و سرور ایران رو روی 5 دقیقه قرار میدادم من چون کلاینت های زیادی داشتم قطع و وصلی زیادی داشت برای همین فقط پنل با کلاینت پایین پیشنهاد میکنم.

**Comment by Azumi67** [comment]
سلام. ریست تایمر بیشتر برای اینکه اگر خطایی پیش اومد و مشکلی در max conn بود با دستور کیل و ریست دوباره پروسه فعال بشه . در هر صورت این تانل ها برای شرایط ایران ساخته نشده و شما باید با لود بالانس فشار رو به حداقل برسونید .
