### ISSUE TITLE
قطعی و نگرفتن پینگ

### ISSUE THREAD

**Issue by KanekiDevPro** [Azumi67/Direct_Chisel#7]
سلام وقت بخیر تانل دو تا سرور خارج زدیم به یه ایران که دومی سرور به مشکل خوره پورت تانل ها که گفته بودین 
فرق دارن فقط یکی از سرور ها اینجوریه 

![Uploading Screenshot_20240514_111903_Termius.jpg…]()

**Comment by KanekiDevPro** [comment]
![Screenshot_20240514_111903_Termius](https://github.com/Azumi67/Direct_Chisel/assets/141396498/cd0c5800-86e2-4360-9cac-52829f7b0b06)

**Comment by Azumi67** [comment]
سلام شما دقیقا چیکار کردید ؟ اومدید 6to4 انجام دادید و بعد دایرکت چیزل استفاده کردید ؟ خب خطاهای تانل چیزل کجا هست ؟

**Comment by KanekiDevPro** [comment]
ip6ip6 + chisel
هر دو ایپی تو ایران و خارج دوم پینگ میدن ولی قطع شده فقط اونم سرور دوم سرور اول مشکلی نداره و اینکه سرور دوم پینگ رو داخل چیزل نمیده بعضی موقع ها داخل عکس هست دلیل چیه

**Comment by Azumi67** [comment]
خب ممکنه‌ سرور دوم شما با ip6ip6 اختلال داشته باشه یا اصلا مشکل دیگری باشه . باید لاگ های چیزل هم به صورت کامل آنالیز کنید .
